version: '2'

services:
  web:
    restart: always
    build: ./docsbox
    expose:
      - "8000"
    links:
      - redis:redis
    volumes:
      - ./docsbox:/home/docsbox
      - /tmp/media:/home/docsbox/media
    command: gunicorn -b :8000 --reload docsbox:app

  rqworker_default:
    restart: always
    build: ./docsbox
    links:
      - redis:redis
    volumes_from:
      - web
    command: rq worker default -c docsbox.settings

  rqworker_low:
    restart: always
    build: ./docsbox
    links:
      - redis:redis
    volumes_from:
      - web
    command: rq worker low -c docsbox.settings

  rqworker_high:
    restart: always
    build: ./docsbox
    links:
      - redis:redis
    volumes_from:
      - web
    command: rq worker high -c docsbox.settings

  rqscheduler:
    restart: always
    build: ./docsbox
    links:
      - redis:redis
    volumes_from:
      - web
    command: rqscheduler -H redis -p 6379 -d 0

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - ${LOCAL_PORT}:80
    volumes_from:
      - web
    links:
      - web:web

  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
    volumes:
      - ./redisdata:/data
